# Generated by Django 4.2.5 on 2023-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_lead_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
