# Generated by Django 4.2.5 on 2023-09-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_lead_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="estimatedCommission",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15
            ),
        ),
    ]
